name: Run Test App tunnel-server on SuperProtocol

on: workflow_dispatch

env:
  ORDER_ID: ''
  SOLUTION_DATA_FILE: ''
  LAST_ORDER_FILENAME: last-orders.txt
  BASE_IMAGE_OFFER: ''
  TUNNEL_SERVER_OFFER: ''
  STORAGE_OFFER: ''
  SOLUTION_NAME: superpotocol-test-app-tunnel-server

jobs:
  start-tunnel-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      repository-projects: read

    steps:
      - name: Check secrets and variables
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "Error: GH_TOKEN secret is missing. Workflow will fail."
            exit 1
          elif [ -z "${{ secrets.SOLUTION_SERVER_TOKEN }}" ]; then 
            echo "Error: SOLUTION_SERVER_TOKEN secret is missing. Workflow will fail."
            exit 1
          elif [ -z "${{ secrets.SPCTL_CONFIG_BASE64 }}" ]; then 
            echo "Error: SPCTL_CONFIG_BASE64 secret is missing. Workflow will fail."
            exit 1
          fi

      - name: Get previous build for solution
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_ACTION_REPOSITORY: ${{ github.repository }}
          GH_WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          LAST_RUN_ID=$(gh run --repo ${{ env.GH_ACTION_REPOSITORY }} list --workflow "${{ env.GH_WORKFLOW_NAME }}" -s success --json databaseId --jq .[0].databaseId)
          gh run --repo ${{ env.GH_ACTION_REPOSITORY }} download $LAST_RUN_ID -n last-orders
          echo "Artifact downloaded"
          ls -la

      - name: Download SPCTL
        run: |
          curl -L https://github.com/Super-Protocol/ctl/releases/download/v0.8.2/spctl-linux-x64 -o ./spctl 
          chmod +x ./spctl

          SPCTL_CONFIG=$(echo "${{ secrets.SPCTL_CONFIG_BASE64 }}" | base64 --decode)
          BASE_IMAGE_OFFER=6,2
          TUNNEL_SERVER_OFFER=10,9
          STORAGE_OFFER=23,27
          echo "$SPCTL_CONFIG" > ./config.json

          echo "Spctl" version
          ./spctl --version

          echo "BASE_IMAGE_OFFER=$BASE_IMAGE_OFFER" >> $GITHUB_ENV
          echo "TUNNEL_SERVER_OFFER=$TUNNEL_SERVER_OFFER" >> $GITHUB_ENV
          echo "STORAGE_OFFER=$STORAGE_OFFER" >> $GITHUB_ENV

      - name: Prepare tunnel server data
        if: env.SOLUTION_NAME == 'superpotocol-test-app-tunnel-server'
        run: |
          mkdir solution-data
          echo "${{ secrets.SOLUTION_SERVER_TOKEN }}" > solution-data/auth-token
          SOLUTION_DATA_FILE=${{ env.SOLUTION_NAME }}-server-data-b${{ github.run_id }}.tar.gz
          tar -czf $SOLUTION_DATA_FILE.tar.gz -C solution-data/ .
          ./spctl files upload $SOLUTION_DATA_FILE.tar.gz --output $SOLUTION_DATA_FILE.json --filename $SOLUTION_DATA_FILE.tar.gz

          echo "SOLUTION_DATA_FILE=$SOLUTION_DATA_FILE.json" >> $GITHUB_ENV

      - name: Run tunnel server for ${{ env.SOLUTION_NAME }}
        run: |
          if [ -f ${{ env.LAST_ORDER_FILENAME }} ]; then
            echo "${{ env.LAST_ORDER_FILENAME }} file found"
            PREVOIUS_ORDER=$(grep "^${{ env.SOLUTION_NAME }}=" ${{ env.LAST_ORDER_FILENAME }} | cut -d'=' -f2)
            if [[ -n "$PREVOIUS_ORDER" ]]; then
              echo "Cancelling order $PREVOIUS_ORDER"
              ./spctl orders cancel $PREVOIUS_ORDER || true
            fi
          fi

          ./spctl workflows create --tee 1 --solution ${{ env.BASE_IMAGE_OFFER }} --solution ${{ env.TUNNEL_SERVER_OFFER  }} --data ${{ env.SOLUTION_DATA_FILE }} --storage ${{ env.STORAGE_OFFER }} --orders-limit 10000 --min-rent-minutes 60 > workflow_result.txt

          cat workflow_result.txt

          ORDER_ID=$(cat workflow_result.txt | grep -oP '\["\K\d+(?="\])') 

          echo "ORDER_ID=$ORDER_ID" >> $GITHUB_ENV

          if grep ${{ env.SOLUTION_NAME }}= ${{ env.LAST_ORDER_FILENAME }}; then
            echo "Updating exitsed row ${{ env.SOLUTION_NAME }}"
            sed -i "s/^${{ env.SOLUTION_NAME }}=.*$/${{ env.SOLUTION_NAME }}=$(echo $ORDER_ID)/" ${{ env.LAST_ORDER_FILENAME }}
          else
            echo "adding new row ${{ env.SOLUTION_NAME }}"
            echo "${{ env.SOLUTION_NAME }}=$ORDER_ID" >> ${{ env.LAST_ORDER_FILENAME }}
          fi

      - name: Archive created order
        uses: actions/upload-artifact@v3
        with:
          name: last-orders
          path: ${{ env.LAST_ORDER_FILENAME }}

      - name: Result
        run: |
          if [ -n "${{ env.ORDER_ID }}" ]; then
            echo "Order succesfully created. Order id: ${{ env.ORDER_ID }}"
          else
            echo "Failed to create order"
            exit 1
          fi
