version: '3.8'

services:
  sp-minecraft:
    image: node:16-buster
    container_name: sp-minecraft
    platform: linux/amd64
    environment:
      - HTTPS_PORT=8888
    volumes:
      - ./:/sp/run
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        yarn --cwd /sp/run start
    ports:
      - '8888:8888'
