version: '3.8'

services:
  sp-minecraft:
    image: sp-minecraft:0.0.1
    container_name: sp-minecraft
    environment:
      HTTPS_PORT: 8888
      TLS_CERT:
      TLS_KEY:
    build: .
    #volumes:
    #  - ${HOME}/minecraft/world:/app/world
    ports:
      - "8888:8888"