/* eslint-disable max-len */
import Link from 'next/link';
import classes from './InfoAccordion.module.scss';

export const intoList: { title: string; content: JSX.Element; eventKey: string; }[] = [
  { title: 'What is Super Protocol?', content: <div>Super Protocol is the confidential cloud and marketplace for Web3. The mission of Super Protocol is to enable developers to build better and more complex Web3 applications (dApps) by utilizing the power of decentralized confidential computing.</div>, eventKey: '0' },
  { title: 'What is this chat?', content: <div>This Web3 chat is a technological demo developed by the Super Protocol team. By this example we want to show how complex dynamic web apps can be run in decentralized confidential environments (TEE).</div>, eventKey: '1' },
  { title: 'What is confidential computing?', content: <div>Confidential computing is the animal-friendly version of a sealed box with Schrödinger&apos;s cat inside. This box is called Trusted Execution Environment (TEE) and it’s protected by the server’s special hardware. This secure box cannot be opened by any unauthorized third parties.</div>, eventKey: '2' },
  { title: 'How is it decentralized?', content: <div>Super Protocol has no single point of failure. First of all, confidential compute machines are sourced from multiple cloud providers (as opposed to centralized CSPs which are limited to their own data centers). This ensures that no single authority can shut down your deployment. Second, data is saved to decentralized databases. And third, of course, Super Protocol runs on blockchain.</div>, eventKey: '3' },
  { title: 'Why is this special?', content: <div>Web3 decentralized applications (dApps) are built using smart-contracts, which are simple and very limited apps running on-chain. Super Protocol expands the capabilities of Web3 by adding a decentralized off-chain computing layer which may be used by dApps to perform any types of complex computations in full confidentiality, beyond the limits imposed by smart-contracts.</div>, eventKey: '4' },
  { title: 'What is Testnet 4?', content: <div>Super Protocol is still in the testnet phase - we are adding new functionality all the time. Everyone is welcome to join and deploy their own chat. Please follow <Link href="https://docs.superprotocol.com/testnet/" className={classes.link} target="_blank">this link</Link> to register.</div>, eventKey: '5' },
  { title: 'I want to build on Super Protocol', content: <div>Great! As it happens, we are now looking for developers who are passionate about Web3 technologies and curious about confidential computing to start creating their apps on Super Protocol – with the full support of our team. Please go <Link href="https://docs.superprotocol.com/developers" className={classes.link} target="_blank">here</Link> to learn more.</div>, eventKey: '6' },
  { title: 'How do I report a problem?', content: <div>Nobody’s perfect and this chat is still an experimental release. If you see something that doesn’t look right, please tell us and we will fix it! You can contact us through <Link href="https://discord.com/invite/superprotocol" className={classes.link} target="_blank">Discord</Link>.</div>, eventKey: '7' },
];
